### ISSUE TITLE
请教下 RuleEngine 在日志处理中的应用.

### ISSUE THREAD

**Issue by kalavt** [rulego/rulego#65]
我目前收集来的日志五花八门
1. 从各系统中收集来的日志 (第三方系统 Audit log)
2. 从业务程序中收集的日志 (JAVA, python, golang, Nginx)
3. 从机器节点上搜集的日志 (journald, auth, dmsg)
以上日志格式不统一. 但各自有各自的规范.
目前是通过日志搜集器, filebeat etc. 将其一股脑塞入 Kafka 中, 后续通过模糊匹配来查询, 这样效率低下

我在想是否已一款规则引擎, 可以满足 输入 -> 匹配/过滤 -> 转化 -> 发送
比如 
Nginx logs 
2015-05-12 12:00 - POST - URL - 200 
JAVA
2025-05-12 12:00:00Z | ERROR | thread-1 | com.java.xxx.xxx | line 12 | Exception NPE.
....

```
rule:
 filter:
  type: regex
  value: ^(<?match_time>2025-05-12) - (<? match_method >\w+) - (<?match_URI>.*) - (<?match_status>\d+4)
 transformer:
  {'time':$match_time | default, 'method': '$match_method | default "GET" ', 'URL': '$match_URL': 'match_URI|default ""', 'status_code':"$match_status"


rule:
 filter:
  type: lua
  value: `lua script`
 transformer:
  {'time':$match_time | default, 'level': '$match_code | default "DEBUG" ', 'thread': '$class': 'match_class|default ""', 'msg':"$match_msg"


```
 
刚好看到了您这个项目.
想请教下, 如果要实现以上功能, 我该从哪里入手?
